name: build-and-push-images

on:
  push:
    branches:
      - deployment

env:
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login to docker
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build docker images
        run: make build-prod

      - name: Push images to docker hub
        run: make push-prod-images